sample_posisition: [1, 2, 3, 4] # not used!

### LINE 55
clr55_pickup:
  frame_id: map
  pose: [9.800989, 57.339683, 0.010018, 0.99995]

clr55_to_line55:
  frame_id: map
  pose:
  - [24.482645, 62.616413, -0.006922, 0.999976]
  - [92.209618, 60.281773, -0.708872, 0.705337]
  - [93.107355, 44.871062, 0.014539, 0.999894]

line55_pickup:
  frame_id: map
  pose: [92.788596, 45.528704, 0., 1.]

line55_to_clr55:
  frame_id: map
  pose:
  - [87.39164, 62.662071, 1.0, 0.00027]
  - [21.869658, 60.563278, -0.72717, 0.686458]
  - [9.832416, 54.641224, -0.70682518, 0.70738827]


### LINE56
clr56_pickup:
  frame_id: map
  pose: [9.800989, 56.881773, 0.01251, 0.999922]

clr56_to_line56:
  frame_id: map
  pose:
  - [25.079063, 62.603859, -0.009965, 0.99995]
  - [67.134399, 58.675545, -0.699012, 0.71511]
  - [85.467207, 48.830773, 0.708727, 0.705483]

line56_pickup:
  frame_id: map
  pose: [85.513332, 48.210142, -0.690715, 0.723127]

line56_to_clr56:
  frame_id: map
  pose:
  - [64.280991, 62.617485, 0.999997, 0.002505]
  - [21.64933, 59.653297, -0.731221, 0.68214]
  - [9.333315, 54.632307, 0.010018, 0.99995]
  

### CHARGER
charger_goal:
  frame_id: map
  pose: [-108.957413, -189.344744, 0.008791, 0.999961]